### ISSUE TITLE
Undeprecate this library?

### ISSUE THREAD

**Issue by btakita** [mbostock/smash#32]
smash does things rollup won't do...

https://github.com/rollup/rollup/issues/445

**Comment by btakita** [comment]
what do you think about making this compatible with rollup?

i.e. `rollup-plugin-smash`

**Comment by mbostock** [comment]
Sorry, but I have no plans to de-deprecate this library, and recommend using the standard (ES6 modules) to write modular code rather than SMASH’s hacky concatenation system.

**Comment by btakita** [comment]
i empathize with your recommendation, however concatenation is a useful tool in a number of circumstances involving legacy javascript & project inertia.

think of this as a bridge to es6 modules...

**Comment by btakita** [comment]
we have a winner with using a json file to specify the files to be built

rip smash
