### ISSUE TITLE
Support reading from standard input

### ISSUE THREAD

**Issue by thejonan** [mbostock/smash#33]
Currently it is not possible to use the tool with a pipe command, because it simply doesn't support reading from the standard input.

In addition, providing `/dev/stdin` automatically leads to trying to access `/dev/stdin.js`.

**Comment by mbostock** [comment]
Sorry, but this repository is deprecated and I am no longer maintaining it. I recommend [Rollup](http://rollupjs.org/).

**Comment by thejonan** [comment]
Yes, I've just noticed that. I'm sorry.
